name: Upload www

on:
  push:
    branches:
      - main

env:
  GOOGLE_ADS_ID: ${{ secrets.GOOGLE_ADS_ID }}
  GOOGLE_TM_ID: ${{ secrets.GOOGLE_TM_ID }}
  GOOGLE_GA_ID: ${{ secrets.GOOGLE_GA_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: aws
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: "0.64.0"

    - name: Pre-build
      run: cd www/themes; sh geekblog.sh

    - name: Pre-build phase2
      run: cd www/layouts; sh apply-custom.sh

    - name: Build
      # remove --minify tag if you do not need it
      # docs: https://gohugo.io/hugo-pipes/minification/
      run: cd www; hugo

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy static site to S3 bucket
      run: aws s3 sync ./www/public/ s3://${{ secrets.AWS_S3_BUCKET_WWW }}/ --delete --acl public-read

    - name: Invalidate CloudFront cache
      run: aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CF_DISTRIBUTION_ID }} --paths "/*"
